//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akida_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Info
    {
        public Category_Info()
        {
            this.Managements = new HashSet<Management>();
        }
    
        public int ID_Category { get; set; }
        public string Name { get; set; }
        public System.DateTime Created_Time { get; set; }
        public string Description { get; set; }
        public int Enabled { get; set; }
    
        public virtual ICollection<Management> Managements { get; set; }
    }
}
