//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akida_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Management
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Category_ID { get; set; }
        public string Author { get; set; }
        public System.DateTime Created_Time { get; set; }
        public string Short_Description { get; set; }
        public int Number_Of_Participants { get; set; }
        public int Video_Info_ID { get; set; }
        public int Cost_Aki { get; set; }
        public int Enabled { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
    
        public virtual Category_Info Category_Info { get; set; }
        public virtual Video_Info Video_Info { get; set; }
    }
}
