//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akida_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int ID_Role { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Allowed_Actions { get; set; }
        public string Role_Name { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
