//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akida_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int ID_User { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Activated { get; set; }
        public System.DateTime Created_Time { get; set; }
        public int AKIDA_Number { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
