//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akida_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_Info
    {
        public Video_Info()
        {
            this.Managements = new HashSet<Management>();
        }
    
        public int ID_Videos { get; set; }
        public string Main_Link_ID { get; set; }
        public int Number_Of_Video { get; set; }
    
        public virtual ICollection<Management> Managements { get; set; }
    }
}
