//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akida_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_Detail
    {
        public string Main_Link { get; set; }
        public string Chapter { get; set; }
        public string Sub_Link { get; set; }
        public int Video_Number { get; set; }
        public int ID { get; set; }
    }
}
